### PR TITLE
fix: refactor producer/consumer design

### LINKED ISSUE #24: split producer/consumer more cleanly
[See comments in zulip](https://github-metrics.zulipchat.com/#narrow/stream/291433-general/topic/generalize.20producer.2Fconsumer)

### PR DESCRIPTION
**Pull request by chazkiker2**
# Description

- closes #24 
- re-structure the producer/consumer pattern for better more approachable re-use

### CODE REVIEW

File: src/metrics.rs [hunk 1]
```diff
@@ -0,0 +1,244 @@
...
+                        "Ran into an issue while counting PRs for repository {}: {}",
+                        &repo.name, e
+                    );
+                }
+            }
+        }
+    }
+
+    // `self` has an anonymous lifetime `'_` but it needs to satisfy a `'static` lifetime requirement
+    fn spawn_producer_task(&self, tx: Sender<Vec<String>>) {
```
Comment (chazkiker2) [inline src/metrics.rs:75]: this code does not compile due to the errors described in [this Zulip message](https://github-metrics.zulipchat.com/#narrow/stream/291433-general/topic/generalize.20producer.2Fconsumer/near/242951396)

Comments for error are included in code currently.

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
Actually I changed my mind. Let's manage that in a follow-up PR.
